-- ============================================================
-- ALAS · Repartidores (para la Calculadora de Flete)
-- Ejecutar en el SQL Editor del proyecto de Flete (wooihkyzpexxqkwwnylt).
-- Aditivo: no borra ni cambia datos existentes.
-- ============================================================

create table if not exists repartidores (
  id     bigint generated by default as identity primary key,
  nombre text not null unique,
  activo boolean not null default true,
  created_at timestamptz default now()
);

alter table repartidores enable row level security;
drop policy if exists anon_all on repartidores;
create policy anon_all on repartidores for all to anon using (true) with check (true);

grant usage on schema public to anon, authenticated;
grant all on repartidores to anon, authenticated;
grant all on all sequences in schema public to anon, authenticated;

-- ── Seed de repartidores ──
-- Cuando me pases la lista de nombres, se agregan acá. Ejemplo:
-- insert into repartidores (nombre) values
--   ('Juan Pérez'),('María López')
-- on conflict (nombre) do nothing;
--
-- (También podés cargarlos desde la Calculadora con el botón "＋ Agregar nuevo".)
