-- ============================================================
-- ALAS Calculadora de Flete — esquema Supabase
-- Ejecutar TODO en el SQL Editor del proyecto nuevo.
-- ============================================================

create table if not exists transportistas (
  id bigint generated by default as identity primary key,
  nombre text not null,
  activo boolean not null default true,
  created_at timestamptz default now()
);

create table if not exists camiones (
  id bigint generated by default as identity primary key,
  transportista_id bigint references transportistas(id) on delete cascade,
  descripcion text not null,
  tipo text not null default 'km',
  precio numeric not null default 0,
  last_km numeric not null default 0,
  created_at timestamptz default now()
);
create index if not exists idx_camiones_ts on camiones(transportista_id);

create table if not exists repartos (
  id bigint generated always as identity primary key,
  fecha date,
  transportista_id bigint,
  transportista_nombre text,
  camion_id bigint,
  camion_descripcion text,
  km numeric default 0,
  precio numeric default 0,
  tipo text,
  total_flete numeric default 0,
  total_monto numeric default 0,
  inc_total numeric,
  gasto_permitido numeric default 0,
  diferencia numeric default 0,
  zona text,
  clientes jsonb default '[]'::jsonb,
  created_at timestamptz default now()
);
create index if not exists idx_repartos_fecha on repartos(fecha);

-- ── Flota (transportistas + camiones) ──
insert into transportistas (id,nombre,activo) values
  (1,'ALAS',true),
  (2,'SL',true),
  (3,'BG',true),
  (4,'CR',true),
  (5,'TRANSMAQ ORTEGA',true),
  (6,'ANTONIO BAEZ',true),
  (7,'JYL',true),
  (8,'GUALEX',true),
  (9,'SAN FRANCISCO',true),
  (10,'MIRANDA',true),
  (11,'BAEZ TRANSPORTE',true),
  (12,'MARECO',true),
  (13,'DM',true),
  (14,'CELSO ORTIZ',true),
  (15,'DI MONTI',true),
  (16,'MYM',true),
  (17,'LUIS ALBERTO',true),
  (18,'KYRE''Y',true),
  (19,'SAN MIGUEL',true),
  (20,'RICARDO DIAZ MARTINEZ',true),
  (21,'GROUP TEO S.A',true),
  (22,'TRANSPORTE SURE',true),
  (23,'VILLALBA',true),
  (24,'GRUA TRANQUI',true),
  (25,'MUNDO TRUK SRL',true),
  (26,'LA CANDELARIA',true),
  (27,'TRANSPORTADORA DF',true),
  (28,'TOMAS VASQUEZ',true),
  (29,'RAMIREZ GIMENEZ',true),
  (30,'AAYV',true),
  (31,'GUSTAVO VELAZQUEZ',true),
  (32,'TRANPORTE PEREIRA',true),
  (33,'TRANSPORTADORA JM',true),
  (34,'CL',true),
  (35,'ATILIO',true),
  (36,'Transportadora Daniela',true),
  (37,'LUIS SANTIAGO SANCHEZ',true)
on conflict (id) do nothing;

insert into camiones (id,transportista_id,descripcion,tipo,precio,last_km) values
  (101,1,'ALAS HYUNDAI','km',0,0),
  (102,1,'ALAS Mercedes Benz 1315 BBH909B','km',0,0),
  (103,1,'ALAS Mercedes Benz 709 AADX129','km',0,0),
  (104,1,'ALAS TRIPLE EJE AARA067','km',0,0),
  (105,1,'ALAS Mercedes Benz 711 AOZ758','km',0,0),
  (106,1,'ALAS FUSO AADP885','km',0,0),
  (107,1,'ALAS Furgon-Foton','km',0,0),
  (201,2,'SL MB814 AAVG562 (SIMPLE)','km',0,0),
  (202,2,'SL MB 914 HDJ075 CELESTE','km',0,0),
  (203,2,'SL MB814 BXC396 BLANCO (RAMPA)','km',0,0),
  (204,2,'SL 914 AYF193 CORTO BLANCO','km',0,0),
  (205,2,'SL MB814 AAPX560 GRIS','km',0,0),
  (206,2,'SL SCANIA DOBLE EJE','km',0,0),
  (301,3,'BG MOVIL 08 HFH-440','km',0,0),
  (302,3,'BG MOVIL 09 AYE-466','km',0,0),
  (303,3,'BG MOVIL 10 AAFI-477','km',0,0),
  (304,3,'BG MOVIL 11 BOZ-074','km',0,0),
  (305,3,'BG MOVIL 13 AAFL-766','km',0,0),
  (306,3,'BG MOVIL 14 XBL-816','km',0,0),
  (307,3,'BG MOVIL 16 AAHK-607','km',0,0),
  (308,3,'BG MOVIL 17','km',0,0),
  (309,3,'BG MOVIL 21 BRX-972','km',0,0),
  (310,3,'BG MOVIL 22 BPD-941','km',0,0),
  (311,3,'BG MOVIL 24 AASI-346','km',0,0),
  (312,3,'BG MOVIL 25 AASI-849','km',0,0),
  (313,3,'BG MOVIL 26 AASM-682','km',0,0),
  (314,3,'BG MOVIL 29 AAIE-232','km',0,0),
  (315,3,'BG MOVIL 31','km',0,0),
  (401,4,'CR Scania 05 AAN498','km',0,0),
  (402,4,'CR Scania 06 HFR039','km',0,0),
  (403,4,'CR Scania 07 BRF403','km',0,0),
  (501,5,'TRANSMAQ VOLKSWAGEN AHN624','km',0,0),
  (502,5,'TRANSMAQ TOYOTA AV6307','km',0,0),
  (503,5,'TRANSMAQ MB814 blanco abierto HBK137','km',0,0),
  (504,5,'TRANSMAQ MERCEDEZ FURGON AZUL','km',0,0),
  (505,5,'TRANSMAQ SCANIA BLANCO ABIERTO','km',0,0),
  (506,5,'TRANSMAQ-SEMI','km',0,0),
  (507,5,'TRANSMAQ GRIS ABIERTO','km',0,0),
  (601,6,'Mercedes Benz Atego 815','km',0,0),
  (602,6,'ANTONIO BAEZ Scania HEU859 VERDE','km',0,0),
  (603,6,'ANTONIO BAEZ Scania ERY582 BLANCO','km',0,0),
  (701,7,'JYL MB815 AAMT094','km',0,0),
  (702,7,'JYL MB814 BSB910 BLANCO','km',0,0),
  (703,7,'JYL MB814 XBK209 AMARILLO','km',0,0),
  (801,8,'GUALEX MB814 AALS926 VERDE','km',0,0),
  (802,8,'GUALEX MB814 CCA037 CELESTE','km',0,0),
  (803,8,'GUALEX M.BENZ 815 GRIS','km',0,0),
  (901,9,'San Francisco MBENZ AABS856 AZUL','km',0,0),
  (902,9,'San Francisco Nissan BNY753','km',0,0),
  (1001,10,'MIRANDA CAMION ANARANJADO CEC580','km',0,0),
  (1002,10,'MIRANDA ROJO MB814 CDTC007','km',0,0),
  (1101,11,'Baez Valentin MBENZ HAR509 BLANCO','km',0,0),
  (1201,12,'SEMI ABIERTO KAE645','km',0,0),
  (1301,13,'SCANIA 113 BYG932','km',0,0),
  (1401,14,'CELSO ORTIZ FOTON YAP978','km',0,0),
  (1402,14,'CELSO ORTIZ SCANIA','km',0,0),
  (1501,15,'DI MONTI ATEGO 815','km',0,0),
  (1601,16,'MYM NISSAN','km',0,0),
  (1602,16,'MYM HINO 711 BSL137','km',0,0),
  (1701,17,'LUIS ALBERTO HYUNDAI B6Y037','km',0,0),
  (1801,18,'KYRE''Y','km',0,0),
  (1901,19,'AAFI Mercedez Benz','km',0,0),
  (1902,19,'Chapa WBZB Caballito / AADH107 Carreta','km',0,0),
  (2001,20,'RD-MB815 DOBLE EJE','km',0,0),
  (2002,20,'RD-MB SENCILLO','km',0,0),
  (2101,21,'GROUP TEO S.A - SEMI','km',0,0),
  (2201,22,'TRANSPORTE SURE - SEMI','km',0,0),
  (2301,23,'VILLALBA - SEMI','km',0,0),
  (2401,24,'TRANQUI - SCANIA CON GRUA','km',0,0),
  (2501,25,'TRUK - CAMION 818 FURGON MB','km',0,0),
  (2601,26,'LA CANDELARIA - SCANIA P230 Triple Eje','km',0,0),
  (2701,27,'DF SCANIA ROJO','km',0,0),
  (2801,28,'Tomás Vasquez - Toyota Granvia','km',0,0),
  (2901,29,'RAMIREZ - MB 814','km',0,0),
  (3001,30,'AAYV SEMI BLANCO','km',0,0),
  (3002,30,'AAYV SCANIA BLANCO','km',0,0),
  (3101,31,'GV MB 814 MARRON','km',0,0),
  (3102,31,'GV-MB HAD746','km',0,0),
  (3201,32,'PEREIRA MBENZ 814 BL','km',0,0),
  (3301,33,'JM MB 814 BLANCO','km',0,0),
  (3302,33,'JM MB 814 INOX','km',0,0),
  (3401,34,'CL SEMI','km',0,0),
  (3501,35,'ATILIO SCANIA AZUL','km',0,0),
  (3601,36,'Daniela - MB1317','km',0,0),
  (3602,36,'Daniela - MB814','km',0,0),
  (3701,37,'MB 914 BLANCO','km',0,0)
on conflict (id) do nothing;

-- Continuar las secuencias despues de los ids sembrados
select setval(pg_get_serial_sequence('transportistas','id'), (select coalesce(max(id),1) from transportistas));
select setval(pg_get_serial_sequence('camiones','id'), (select coalesce(max(id),1) from camiones));

-- ── RLS: acceso anon (patron del ecosistema) ──
alter table transportistas enable row level security;
alter table camiones enable row level security;
alter table repartos enable row level security;
do $$ declare t text; begin
  foreach t in array array['transportistas','camiones','repartos'] loop
    execute format('drop policy if exists anon_all on %I;', t);
    execute format('create policy anon_all on %I for all to anon using (true) with check (true);', t);
  end loop; end $$;
