-- ============================================================
-- ALAS · UNIFICACIÓN Flete + Control de Facturas
-- Se ejecuta en el proyecto de la CALCULADORA DE FLETE (wooihkyzpexxqkwwnylt).
-- Convierte `repartos` (de Flete) en la PLANILLA que consume Control de Facturas
-- y agrega las tablas de gestión (facturas / auditoría / reporte).
--
-- Cómo correrlo:  SQL Editor de Supabase (proyecto Flete) → pegar TODO → Run.
-- Es idempotente y ADITIVO: no borra ni altera los datos existentes de Flete.
-- ============================================================

-- ============================================================
-- 1) repartos = PLANILLA: columnas nuevas para Control
-- ============================================================
alter table repartos add column if not exists semana_desde date;
alter table repartos add column if not exists semana_hasta date;
alter table repartos add column if not exists estado       text not null default 'abierta';  -- abierta | auditoria
alter table repartos add column if not exists factura_id   bigint;   -- factura asignada (fact_facturas.id)

-- CHECK del estado (guardado, idempotente)
do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'repartos_estado_chk') then
    alter table repartos add constraint repartos_estado_chk check (estado in ('abierta','auditoria'));
  end if;
end $$;

-- Semana (lunes–domingo) derivada de la fecha. date_trunc('week') = lunes (ISO).
update repartos
   set semana_desde = date_trunc('week', fecha)::date,
       semana_hasta = (date_trunc('week', fecha) + interval '6 days')::date
 where fecha is not null and semana_desde is null;

create index if not exists idx_repartos_semana on repartos(semana_desde);

-- ============================================================
-- 2) Facturas (llega y se asigna a una planilla = repartos.id)
-- ============================================================
create table if not exists fact_facturas (
  id                    bigint generated by default as identity primary key,
  nro                   text,
  fecha                 date,
  transportadora_id     bigint,
  transportadora_nombre text,
  monto                 numeric default 0,
  planilla_id           bigint,          -- ref lógica → repartos.id
  created_at            timestamptz default now()
);
create index if not exists idx_fact_facturas_planilla on fact_facturas(planilla_id);

-- ============================================================
-- 3) Auditoría (bitácora de acciones de Control)
-- ============================================================
create table if not exists fact_audit (
  id          bigint generated by default as identity primary key,
  ts          timestamptz not null default now(),
  accion      text not null,
  usuario     text,
  detalle     text,
  chips       text[] default '{}',
  planilla_id bigint,                  -- ref lógica → repartos.id
  created_at  timestamptz default now()
);
create index if not exists idx_fact_audit_ts on fact_audit(ts desc);
create index if not exists idx_fact_audit_planilla on fact_audit(planilla_id);

-- ============================================================
-- 4) Reporte General (valores manuales por mes; flete/km/monto salen de repartos)
--    'data' = JSON con la carga manual (facturación general + por segmento).
-- ============================================================
create table if not exists fact_reporte (
  mes        text primary key,           -- 'YYYY-MM'
  data       jsonb not null default '{}',
  created_at timestamptz default now()
);

-- ============================================================
-- 5) RLS + GRANTS para las tablas nuevas (patrón del ecosistema)
--    (repartos/transportistas/camiones ya tienen RLS del schema de Flete)
-- ============================================================
alter table fact_facturas enable row level security;
alter table fact_audit    enable row level security;
alter table fact_reporte  enable row level security;

do $$ declare t text; begin
  foreach t in array array['fact_facturas','fact_audit','fact_reporte'] loop
    execute format('drop policy if exists anon_all on %I;', t);
    execute format('create policy anon_all on %I for all to anon using (true) with check (true);', t);
  end loop; end $$;

grant usage on schema public to anon, authenticated;
grant all on all tables    in schema public to anon, authenticated;
grant all on all sequences in schema public to anon, authenticated;
alter default privileges in schema public grant all on tables    to anon, authenticated;
alter default privileges in schema public grant all on sequences to anon, authenticated;

-- ============================================================
-- FIN. repartos ahora es la planilla (con semana/estado/factura_id).
-- Nuevas: fact_facturas, fact_audit, fact_reporte.
-- ============================================================
